### ISSUE TITLE
Edit generated styles in dev tools

### ISSUE THREAD

**Issue by Duskfall** [Khan/aphrodite#314] opened 2018-03-21 15:19 UTC
Is there a way to edit the generated styles in chrome dev tools? Currently they are grayed out, which decreases development time.
![image](https://user-images.githubusercontent.com/2528125/37718701-ff9d49cc-2d2b-11e8-91ea-0f356a4a9403.png)

**Comment by dmiller9911** [comment] 2018-03-23 13:10
Does a refresh help?  I sometimes see this if I have them open and things change.  Usually, a refresh will resolve it. I have seen this with other css-in-js libs before and never could pin down why it was doing it.

**Comment by jjmax75** [comment] 2018-03-28 17:25
same here, can't turn off styles or edit in dev tools

**Comment by RetroBum** [comment] 2018-04-08 09:57
Same problem here so swapped aphrodite for version 1.2.0 I had used in an old project where this worked.

**Comment by austenpayan** [comment] 2018-06-14 16:18
I'm also experiencing this on Chrome and Safari. It seems to be Chrome/Webkit specific, as I can still edit the styles in Firefox.

**Comment by lencioni** [comment] 2018-06-14 16:29
I think this is caused by the same thing as #321. More information in this comment: https://github.com/Khan/aphrodite/issues/321#issuecomment-396730606

**Comment by mbensch** [comment] 2018-07-30 18:51
@lencioni This is likely caused by #240 since the `<style>` tag is no longer populated with the actual css rules.

**Comment by lencioni** [comment] 2018-07-30 20:59
Indeed

**Comment by lencioni** [comment] 2020-06-29 21:49
This has been fixed in Chrome 85: https://developers.google.com/web/updates/2020/06/devtools

**Closed by lencioni** 2020-06-29 21:49 UTC

**Comment by k-funk** [comment] 2022-01-05 19:53
This is still a problem in Safari.
