### ISSUE TITLE
Support for attribute selectors

### ISSUE THREAD

**Issue by ostrgard** [Khan/aphrodite#35] opened 2016-03-29 14:52 UTC
Hi!

There's currently no support for [attribute selectors](https://www.w3.org/TR/CSS2/selector.html#attribute-selectors). I could make a small PR with support and tests for this, if you're interested, unless it's left out by design?

**Comment by xymostech** [comment] 2016-03-29 16:03
I think that it is left out by design. Is there a reason why you would need to be testing for selectors and couldn't just be conditionally adding more styles? I assume the attributes are being added to the element that you are styling, so you should have access to them, no?

**Comment by ostrgard** [comment] 2016-04-03 10:12
I don't have a specific use case for this, I just saw it as a low hanging fruit to cover more of the CSS spec.

**Comment by kentcdodds** [comment] 2016-04-07 04:19
Yeah, from my (user) perspective, the more I use this, the more I come to realize that the idea of this library is to associate styles with specific elements (components) in an explicit way rather than the implicit nature of CSS. So there actually is no concept of selectors at all. It's all about taking styles and applying them directly to components.

This is still taking some getting used to for me, but the more I use aphrodite, the more I buy into the concept. :+1:

**Comment by xymostech** [comment] 2016-04-07 06:18
@kentcdodds Glad you're enjoying the library!

I agree, so I'm going to close this, because we don't want o support attribute selectors.

**Closed by xymostech** 2016-04-07 06:18 UTC
