### ISSUE TITLE
0.3.2 does not work

### ISSUE THREAD

**Issue by goatslacker** [Khan/aphrodite#86] opened 2016-06-07 01:32 UTC
Looks like your main is `lib/index.js` but you're publishing stuff in `dist/` now? 0.3.1 works just fine.

**Comment by goatslacker** [comment] 2016-06-07 01:35
it might just be that ya'll didn't npm publish the `lib` directory.

**Comment by goatslacker** [comment] 2016-06-07 01:35
I recommend a `prepublish` script :)

**Comment by kentcdodds** [comment] 2016-06-07 01:41
Thanks for reporting @goatslacker! Looks like the problem is probably the new `.gitignore`. I recommend that we actually add a [`files`](https://docs.npmjs.com/files/package.json#files) property to the `package.json` so we can explicitly list the files we want added (probably `dist` is all that's needed there).

**Comment by jlfwong** [comment] 2016-06-07 01:42
Thanks for the report! Will investigate and fix.

**Comment by kentcdodds** [comment] 2016-06-07 01:44
Also, on the subject of `prepublish`, the workflow did have `prepublish` before, but I filed [a pull request](https://github.com/Khan/aphrodite/pull/55) referencing https://github.com/npm/npm/issues/3059 as a reason to remove the `prepublish` script. I have since learned that I misunderstood how `prepublish` works (which is reasonable because it's a bit confusing) and it's actually not too bad a solution after all. See [my explanation](https://www.youtube.com/watch?v=q2VmFz9VUJ0).

**Comment by kentcdodds** [comment] 2016-06-07 01:45
Also, I feel compelled to bring up [`semantic-release`](https://github.com/semantic-release/semantic-release) again. Even though semantic-release technically wouldn't have prevented this, I still feel like it'd be a good thing to implement for various other human-error reasons :-)

**Comment by kentcdodds** [comment] 2016-06-07 01:46
Oh, and one other thing, just for completeness, let's make sure that 0.3.2 is [deprecated](https://docs.npmjs.com/cli/deprecate)

**Comment by jlfwong** [comment] 2016-06-07 01:52
@kentcdodds I regret to say that I haven't taken the time to investigate semantic-release with any depth, but fear that the automatic version setting based on running against previous versions of the test suite will end up being more burdensome than helpful when not established from the get-go.

Thanks for the note about `npm deprecate`, I hadn't seen that before!

**Comment by jlfwong** [comment] 2016-06-07 01:58
Okay, I've repro'd the issue and think I understand the problem. Here's what happened:

1. I cloned the repo fresh, having not set it up on my laptop before
2. I ran `npm version` to bump the versionn
3. I ran `git push` (this step is actually irrelevant, but just for completeness)
4. I ran `npm publish`.

The key thing is that `npm build` was not run anywhere in here, which is the problem. `lib` is intentionally not checked into the repository, but it is important that it happens before publish.

So the problem is in process, not in the codebase. Both the `.gitignore` and the `.npmignore` are correct (since the `.npmignore` trumps the `.gitignore`, allowing the `lib` directory to be published).

**Comment by kentcdodds** [comment] 2016-06-07 02:02
Oh, I just realized that the reason the build wasn't run is because the script `version` isn't run when you run `npm version` (only when you run `npm run version`). So you could add the build as part of a `preversion` script and that would work.

On semantic-release. I've added it to several projects after the initial release (I even demonstrate this in [my egghead course](http://kcd.im/write-oss)) and it works great.

> fear that the automatic version setting based on running against previous versions of the test suite will end up being more burdensome than helpful

Not certain what you mean by this. Care to elaborate?

**Comment by jlfwong** [comment] 2016-06-07 02:03
0.3.3 is published and pushed, 0.3.2 is marked as deprecated.

Thanks for the (incredibly) fast bug report, @goatslacker, and thanks @kentcdodds for chiming in so quickly :)

**Closed by jlfwong** 2016-06-07 02:03 UTC

**Comment by jlfwong** [comment] 2016-06-07 02:12
@kentcdodds the `version` script is run when you run `npm version`. The problem was that 0.3.2 was published *before* I merged that PR (I'm guessing you wrote this before I wrote the comment about that).

> Not certain what you mean by this. Care to elaborate?

Ah, sorry - I misread the description of the package, and assumed the bits about test suite analysis to be part of semantic-release, when it looks like that's actually functionality of a plugin. Looks like by default it just analyzes commit messages.

Others may disagree, but my general stance is to keep dependencies (both in process and in files-that-wind-up-in-the-repo) to a minimum, and so far I'm not seeing it as a big enough win to merit introducing it as a process dependency.

**Comment by kentcdodds** [comment] 2016-06-07 02:17
> I'm guessing you wrote this before I wrote the comment about that

Yup! Thanks for clarifying :-)

> keep dependencies to a minimum

I agree generally

> I'm not seeing it as a big enough win to merit introducing it as a process dependency.

Yeah, this is what I hear most often when encouraging people to give semantic-release a shot. I should probably come up with a better "sales pitch" for the lib. But from my perspective, once `semantic-release` is set up, a whole class of (boring) problems just goes away and one of the most human-error prone aspects of maintaining projects is now automated. semantic-release is one of the most valuable aspects of my OSS workflow.

**Comment by goatslacker** [comment] 2016-06-07 06:13
Thanks for fixing real quick :) I just bumped down to 0.3.1 in the meantime. 0.3.2 was testing my understanding of node, I would cd into a directory and type `require('aphrodite')` in a node REPL and I'd get module does not exist error haha
