### ISSUE TITLE
Bug: classes different depending on the order they were generated

### ISSUE THREAD

**Issue by lazopm** [Khan/aphrodite#235] opened 2017-03-29 18:16 UTC
I ran into this weird bug, when my nav's active item class is generated first, the inactive class also has the active item's `:hover` rule.

See below: 
![screen shot 2017-03-29 at 2 11 17 pm](https://cloud.githubusercontent.com/assets/5622067/24469587/f876aafa-1489-11e7-81bc-8f5a97fd2f34.png)

Stylesheet: 
```javascript
const styles = StyleSheet.create({
    Item: {
        textDecoration: 'none',
        color: 'blue',
        ':hover': {
            color: 'green', 
        },
        fontSize: 24,
        transition: 'color 0.25s ease',
    },
    Item__active: {
        color: 'red',
        ':hover': {
            color: 'red',
        },
    },
});
```

Code here:
https://github.com/lazopm/aphrodite-bug

**Comment by lencioni** [comment] 2017-03-29 18:36
Thanks! This looks like a duplicate of #231.

**Closed by lencioni** 2017-03-29 18:36 UTC
