### ISSUE TITLE
Directing style creation when rendering to iframes

### ISSUE THREAD

**Issue by tolmasky** [Khan/aphrodite#262] opened 2017-08-01 21:37 UTC
In our application, we render to Dom elements in other iframes:

```javascript
React.render(<App/>, iframe.document.getElementById("body"))
```
But the Aphrodite styles get added to the parent instead of the iframe. Is there a way to tell Aphrodite which to use? For example:

```javascript
aphrodite.useStyleSheet(iframe.document.querySelector("style"));
React.render(<App/>, iframe.document.getElementById("body"));
aphrodite.useStyleSheet(backToWhatItWas);
```

**Comment by xymostech** [comment] 2017-08-01 22:02
I think this is a duplicate of #130, which doesn't yet have a solution. You can see the discussion in there for some ideas of how to solve this, but none have been implemented.

**Closed by xymostech** 2017-08-01 22:02 UTC
