### ISSUE TITLE
Is there a way to change the css of an element by hovering on another element ?

### ISSUE THREAD

**Issue by aziz-boudi4** [Khan/aphrodite#145] opened 2016-09-22 02:16 UTC
I'm trying to show hidden content by hovering on a visible element.

I have a visible {p} element and a hidden list {ul}.

how can I make the {ul} list visible by hovering on the {p}  ?

                      

                        const stylesHeader = StyleSheet.create({

                          dropdown : {
                              position: relative;
                             display: inline-block;
                          },

                         dropdown-content : {
                              display: none;
                              position: absolute;
                              background-color: #f9f9f9;
                              min-width: 160px;
                              box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                              padding: 12px 16px;
                           }, 

Can I do something like that ?
I want to display dropdown-content by hovering on dropdown
                           
                            `dropdown: {
                                 "hover": {
                                     dropdown-content {
                                         display: block;
                                      }
                                    }
                                }
                             });`

                              <div className="dropdown">
                                    <span>Hover over me</span>
                                    <div className="dropdown-content">
                                           <p>Test 1</p>
                                           <p>Test 2</p>
                                           <p>Test 3</p>
                                           <p>Test 4</p>
                                    </div>
                                </div>`

**Comment by xymostech** [comment] 2016-09-22 05:11
There isn't a way to do this right now, this is a duplicate of #10, you can read through that to see progress on that and hacks to achieve this right now.

**Closed by xymostech** 2016-09-22 05:11 UTC
