### ISSUE TITLE
`content` property value renders without quotation marks

### ISSUE THREAD

**Issue by romanenko** [Khan/aphrodite#26] opened 2016-03-13 01:56 UTC
Hello.

I specify `content` property for a pseudo-selector like this:

```javascript
//...
  imageWrapLoaded: {
    ':after': {
      content: 'yo',
      position: 'absolute',
//...
```

And it gets inserted into `<style>` without quotation marks:
![2016-03-13 07-51-00 current call](https://cloud.githubusercontent.com/assets/336141/13726426/923aa14e-e8f0-11e5-9401-8353a75b86aa.png) 
and, accordingly, is not rendered.

**Comment by xymostech** [comment] 2016-03-14 17:11
It looks like the value for the `content` property is supposed to be quoted. I.e. the generated CSS should be

```
...:after {
    content: "yo" !important;
}
```

Thanks for reporting, we'll work on it! In the meantime, you could try doing `content: '"yo"'` (note the extra `"`).

**Comment by romanenko** [comment] 2016-03-14 21:04
Thanks, it worked!
Thank you for the awesome lib! It is like CSS Modules, but inline ^^

**Comment by rileyjshaw** [comment] 2016-03-14 22:40
For the record, I like having to specify the quotes explicitly. It matches CSS more closely.

Also, if we ever wanted to do something like `content: attr(data-foo);` we wouldn't want to put quotes around it.

**Comment by spicyj** [comment] 2016-03-14 22:42
+1. When specifying font family names with spaces I would also expect to have to write quotes.

**Comment by xymostech** [comment] 2016-03-15 18:34
Okay, I'm gonna close this since needing to add quotes seems like expected behaviour.

**Closed by xymostech** 2016-03-15 18:34 UTC
