### ISSUE TITLE
Support for other classNames in one CSS class (like ':hover otherClass')

### ISSUE THREAD

**Issue by Skywalker13** [Khan/aphrodite#253] opened 2017-07-03 14:59 UTC
Hello,

Using class with hover like this (I want to change the backgroundColor of an other class):
```js
const otherClass = {
  toto: {
    backgroundColor: 'green'
  }
};

const sheet = StyleSheet.Create (otherClass);
const otherClassName = css (sheet.toto);

const myClass = {
  foobar: {
    [`:hover ${otherClassName}`]: {
      backgroundColor: 'red'
    }
  }
};
```

It's not working... It's should be easy to handle this use case.. no?

Thanks
Regards

**Comment by xymostech** [comment] 2017-07-03 19:48
Sounds like you're trying to do what we've talked about in #10. We haven't come up with a good solution to this as of yet. The code you list should be working, but it's a hack and might break in the future. I can help you debug that. The other solution is to manually keep track of `:hover` state with javascript `onMouseOver`/`onMouseOut` handlers.

(I'm going to close this as a duplicate of #10. I can still help you out with fixing your code, though)

**Closed by xymostech** 2017-07-03 19:48 UTC
