### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by thiamsantos** [Khan/aphrodite#221] opened 2017-03-12 14:10 UTC
Would be great update the readme following the [standard readme](https://github.com/richardlitt/standard-readme) [specification](https://github.com/RichardLitt/standard-readme/blob/master/spec.md). In order to provide a predictable format for facilitate the reading. And seize the opportunity to add an explanation of [why use this project and the CSS in JS technique](https://github.com/Khan/aphrodite/issues/103#issuecomment-233389840).

**Comment by lencioni** [comment] 2017-03-13 15:51
I'm going to close this as a duplicate of #103. Please feel free to add to the discussion over there or open a PR.

**Closed by lencioni** 2017-03-13 15:51 UTC
Labels: duplicate
