### ISSUE TITLE
Minify class names by setting the environment variable process.env.NODE_ENV to the string value production.

### ISSUE THREAD

**Issue by vladtamas** [Khan/aphrodite#285] opened 2017-11-04 15:51 UTC
Hi,

I'm new to node.js and I don;t know how to set the environment variable when I run a script. Can you explain me how should I do it?

**Comment by zgotsch** [comment] 2017-11-09 22:26
**env.js:**
```
const process = require("process");

console.log("NODE_ENV", process.env.NODE_ENV);
```

**Usage:**
```
$ node env.js
NODE_ENV undefined

$ NODE_ENV=production node env.js
NODE_ENV production
```

See also general environment variables [guide](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps), `process.env` [docs](https://nodejs.org/api/process.html#process_process_env), and [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/) if you're using webpack.

**Comment by xymostech** [comment] 2017-11-18 04:57
@vladtamas Let us know if that worked for you or not! I'm going to close this issue, because it's not a bug or feature request having to do with Aphrodite itself.

**Closed by xymostech** 2017-11-18 04:57 UTC
