### ISSUE TITLE
Psuedo styles override other styles

### ISSUE THREAD

**Issue by natew** [Khan/aphrodite#69] opened 2016-05-03 04:00 UTC
We're building a wrapper around aphrodite that makes our lives a bit easier.

One concept we have is styling based on tagname vs classname. And our styler resolves styles based on priority of: tag, class (ordered by appearance in class array or string).

One weird case is psuedo effects. Say I have:

`<tag class="link active" />`

Let's say `link` gives a hover style:

`link: { ':hover': { color: 'red' } }`

But then active should set a new color:

`active: { color: 'blue' }`

Because aphrodite uses a single classname for both the selectors, the hover on the `link` style will override on the `active` color (when hovered of course), and I don't (think) there's a way to override it without manually setting hover in active.

For now I think the only way to fix would be to have our system detect psuedo attributes and auto-add that hover style, but that would be a lot of code/overhead.

Not sure the best way to handle this, one idea would be some under-the-hood style priority key that could potentially use CSS magic to override precedence.

```
{
  link: { _priority: 0, hover: { ...styles } }
  active: { _priority 1, ...styles }
}
```

**Comment by jlfwong** [comment] 2016-05-03 04:49
This seems like expected behavior to me, and I'm not really sure what the ask is.

If you want `active` to override the `:hover` state, then override the `:hover` state, as you mentioned.

I'm having a hard time understanding why you'd want `blue` to prevail as the winner here, but I suspect the answer to that question has to do with the abstractions that you're trying to build.

**Comment by natew** [comment] 2016-05-03 04:53
The ask is pretty simple: to be able to have styles stronger than hover without using another hover.

This is something that's very easy in CSS: just use a stronger selector. Or in other CSS-in-JS libraries like Radium: just use the right order.

But with Aphrodite there's no way to have a stronger style than *any* pseudo selector, unless you use that specific pseudo selector. So it's a simple request for that. I'd be willing to code it, just wanted to discuss implementation.

Otherwise there are some really bad patterns that emerge. If I have 4 styles on a hover, and I want to override all 4 on some state (say, `selected`). I now have to write the same 4 styles twice: once for normal state, and another time for hover.

**Comment by jlfwong** [comment] 2016-05-03 04:58
Sorry, I'm still confused (I'm also unsure if your reply was written before my edit to the post above). I made a jsfiddle to confirm my assumptions about how CSS works: https://jsfiddle.net/9pvLr5hw/

The semantics of Aphrodite, as far as I can tell, match those of CSS. Setting the color of text, and setting the color of text on hover are independent.

As for Radium, Radium's semantics *don't* map to CSS's because it doesn't use real pseudo selectors -- it implements hover in JavaScript using mouse events.

Consider the converse case: what if i want some label to inherit the hover color but to change the non-hover color?

**Comment by natew** [comment] 2016-05-03 05:00
Sure thing, how would you code this in aphrodite:

https://jsfiddle.net/9pvLr5hw/2/

**Comment by jlfwong** [comment] 2016-05-03 05:08
Ahh, interesting. The result of that case is surprising to me, and it looks like I misunderstood how specificity rules apply when combined with pseudo-selectors. Thanks for the clear example!

There is indeed no way to easily do that in Aphrodite.

I'm still not terribly excited by the prospect of adding a priority scheme with more complex mechanics than the deep-merge we have at the moment. What were the semantics you had in mind for determining when a non-hover style should over-ride a hover style? Same priority means you get both, higher priority non-hover style will over-ride hover style as it appears it does in CSS?

**Comment by natew** [comment] 2016-05-03 05:17
No worries, I realized a couple lines of code was better than me going on about it in english!

Also not an exciting feature because it seems to open up a lot of complexity. I think you need some way of prioritizing it though because you need both types of functionality: non-overriding and overriding. And so there has to be some way to indicate it. Perhaps a really simple way would be to not do nesting:

```
{
  // this will be overriden by other styles applied (perhaps only later in the css merge)
  'link:hover': { color: 'red' }
}
```

Otherwise priority key, which is the most flexible but hardest to implement probably.

Actually, just did a test. CSS lets you put the same class twice to trigger precedence (https://jsfiddle.net/9pvLr5hw/3/) so this wouldn't be too bad. Priority == add multiply classname in selector.

Other options would be some sort of explicit thing (just throwing out bad ideas): `{ active: { ':hover': false } }`

**Comment by thisissami** [comment] 2016-11-02 02:02
@natew @jlfwong is this addressed by the code examples given here? https://github.com/Khan/aphrodite#overriding-styles My team is considering using Aphrodite and we're curious about this.

**Comment by natew** [comment] 2017-01-05 16:54
@thisissami it's been a while since I've looked at this, but anecdotally, upgrading to 1.0 seemed to fix a different bug related to this one, so perhaps this is fixed now.

**Comment by lencioni** [comment] 2017-03-11 15:37
I'm closing this issue to clear things out. Please feel free to open it again!

**Closed by lencioni** 2017-03-11 15:37 UTC
